name: Deploy to WordPress.org SVN
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: WordPress.org Plugin Deploy (release)
      if: github.event_name == 'release'
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: elallas-kezelo
        BUILD_DIR: elallas-kezelo

    - name: WordPress.org Plugin Deploy (manual)
      if: github.event_name == 'workflow_dispatch'
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: elallas-kezelo
        BUILD_DIR: elallas-kezelo
        VERSION: ${{ github.ref_name }}
